name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DB_HOST: 127.0.0.1
  DB_USER: chat
  DB_PASSWORD: chat
  DB_NAME: chat
  REDIS_ADDR: 127.0.0.1:6379
  FRONTEND_ORIGIN: '*'

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            go-version: ["1.23", "1.22.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go${{ matrix.go-version }}-

      - name: Run unit tests (-short)
        run: go test -short ./...

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ matrix.go-version }}

  integration:
    if: github.event_name != 'pull_request'
    needs: unit
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: chat
          POSTGRES_USER: chat
          POSTGRES_DB: chat
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U chat"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go1.22-${{ hashFiles('**/go.sum') }}

      - name: Wait for DB / Redis
        run: |
          until pg_isready -h localhost -U $DB_USER; do sleep 2; done
          until redis-cli -h localhost ping; do sleep 2; done

      - name: Run unit + integration tests
        run: go test -tags=integration ./...
